.TH "assets/view/articleView.php" 3 "Fri Jun 26 2020" "Version 1.1" "<Le blog des stars/>" \" -*- nroff -*-
.ad l
.nh
.SH NAME
assets/view/articleView.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBforeach\fP ( $categories as $categorie) = $categorie['nom_categorie']"
.br
.ti -1c
.RI "\fBendforeach\fP = $_SESSION['id']"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "endforeach = $_SESSION['id']"

.PP
Definition at line 22 of file articleView\&.php\&.
.SS "\fBendforeach\fP foreach ( $categories as) = $categorie['nom_categorie']"

.PP
Definition at line 20 of file articleView\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for <Le blog des stars/> from the source code\&.
