.TH "auteur.php" 3 "Fri Jun 26 2020" "Version 1.1" "<Le blog des stars/>" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auteur.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP (isset( $_GET[ 'auteur'])&&!empty( $_GET[ 'auteur']))"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "if(isset($_GET['auteur'])&&!empty($_GET['auteur']))"
Si on a bien un id auteur
.PP
Récupère les articles de l'auteur et les affiche 
.PP
Definition at line 11 of file auteur\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for <Le blog des stars/> from the source code\&.
