.TH "assets/view/categorieView.php" 3 "Fri Jun 26 2020" "Version 1.1" "<Le blog des stars/>" \" -*- nroff -*-
.ad l
.nh
.SH NAME
assets/view/categorieView.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBforeach\fP ( $articles as $article) = strftime('%A %d %B %Y, %H:%M',strtotime($article['created_at']))"
.br
.ti -1c
.RI "\fBendif\fP = substr($article['content'], 0 , 150)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "endif = substr($article['content'], 0 , 150)"

.PP
Definition at line 17 of file categorieView\&.php\&.
.SS "foreach($articles as $article) = strftime('%A %d %B %Y, %H:%M',strtotime($article['created_at']))"

.PP
Definition at line 6 of file categorieView\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for <Le blog des stars/> from the source code\&.
