.TH "assets Directory Reference" 3 "Fri Jun 26 2020" "Version 1.1" "<Le blog des stars/>" \" -*- nroff -*-
.ad l
.nh
.SH NAME
assets Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBpages\fP"
.br
.ti -1c
.RI "directory \fBpartials\fP"
.br
.ti -1c
.RI "directory \fBview\fP"
.br
.in -1c
